UPDATE suppliers SET name='عيد شعبان-لودر', activity='موردين ألات ومعدات' WHERE code=20300086 AND company_id=1;
UPDATE suppliers SET name='جهاز مستقبل مصر للتنمية المستدامة', activity='موردين منتجات زراعية' WHERE code=20900151 AND company_id=1;
UPDATE suppliers SET name='شركة عرفة للتصدير والتنمية الزراعية واستصلاح الاراضي', activity='موردين منتجات زراعية' WHERE code=20900353 AND company_id=1;
UPDATE suppliers SET name='احمد دسوقي-عمالة', activity='موردين عمالة' WHERE code=21400002 AND company_id=1;
UPDATE suppliers SET name='عمرو السمالوسي - لودر', activity='موردين ألات ومعدات' WHERE code=20100033 AND company_id=1;
UPDATE suppliers SET name='ابراهيم رمضان الكيلاوي', activity='موردين عمالة' WHERE code=21400108 AND company_id=1;
UPDATE suppliers SET name='مورد نقدي', activity='موردين متنوعات' WHERE code=20800286 AND company_id=1;
UPDATE suppliers SET name='عميل نقدى', activity='عملاء محليون' WHERE code=10100192 AND company_id=1;
UPDATE suppliers SET name='ميكنة احمد عبيد', activity='موردين ألات ومعدات' WHERE code=20300121 AND company_id=1;
UPDATE suppliers SET name='شركة عرفة للتصدير والاستيراد والتوريدات', activity='موردين متنوعات' WHERE code=35300902 AND company_id=1;
