/**
 * import_nawat_transactions.js
 * Reads نواة_المستقبل_2025-2026.json and imports the 313 transactions
 * into supplier_transactions using NOT EXISTS guards (idempotent).
 *
 * Usage: node import_nawat_transactions.js
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const JSON_FILE = path.join(__dirname, 'نواة_المستقبل_2025-2026.json');
const COMPANY_ID = 1;
const DB_NAME = 'agri-nile-flow-data-lake';

// ─── helpers ────────────────────────────────────────────────────────────────
function esc(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return isNaN(v) ? 'NULL' : String(v);
  // Sanitize strings — prevent SQL injection
  return `'${String(v).replace(/'/g, "''")}'`;
}

function isoDate(v) {
  if (!v) return 'NULL';
  // JSON dates come as "2025-11-17 00:00:00" → keep as-is
  return `'${String(v).slice(0, 10)}'`;
}

// Map JSON النوع to DB entry_type (already in Arabic, just trim)
function entryType(v) {
  if (!v) return 'NULL';
  const t = String(v).trim();
  return esc(t); // 'د' or 'م'
}

// ─── main ────────────────────────────────────────────────────────────────────
const raw = fs.readFileSync(JSON_FILE, 'utf8');
const data = JSON.parse(raw);

const transactions = data['البيان_الرئيسي']['المعاملات'];
console.log(`✅ Loaded ${transactions.length} transactions from JSON`);

// Build SQL statements — each is an INSERT ... WHERE NOT EXISTS
const sqlLines = [];

sqlLines.push('-- Auto-generated by import_nawat_transactions.js');
sqlLines.push(`-- Total source records: ${transactions.length}`);
sqlLines.push('-- Strategy: INSERT WHERE NOT EXISTS (idempotent, safe to re-run)');
sqlLines.push('');

let inserted = 0;
for (const t of transactions) {
  // Skip rows with no financial value and no document_number (truly empty)
  if (
    (t['القيمه'] === 0 || t['القيمه'] === null) &&
    (t['دائن'] === 0) &&
    (t['مدين'] === 0) &&
    !t['رقم المستند']
  ) {
    continue;
  }

  const supplierCode  = t['كود المورد'];
  const txDate        = isoDate(t['التاريخ']);
  const entryTp       = entryType(t['النوع']);
  const docType       = esc(t['نوع المستند']?.trim());
  const docNum        = t['رقم المستند'] != null ? String(t['رقم المستند']) : 'NULL';
  const description   = esc(t['البيان']);
  const expCat        = esc(t['المصروف']);
  const equipment     = esc(t['المعدة']);
  const unit          = esc(t['الوحدة']?.trim());
  const qty           = t['الكميه'] != null ? t['الكميه'] : 'NULL';
  const unitPrice     = t['السعر'] != null ? t['السعر'] : 'NULL';
  const amount        = t['القيمه']  != null ? t['القيمه']  : 0;
  const credit        = t['دائن']    != null ? t['دائن']    : 0;
  const debit         = t['مدين']    != null ? t['مدين']    : 0;
  const checkAmt      = t['الشيكات'] != null ? t['الشيكات'] : 0;
  const dueDate       = isoDate(t['تاريخ الاستحقاق']);
  const balNoChk      = t['الرصيد بدون شيكات'] != null ? t['الرصيد بدون شيكات'] : 'NULL';
  const balWithChk    = t['الرصيد بالشيكات']   != null ? t['الرصيد بالشيكات']   : 'NULL';
  const chkClear      = isoDate(t['تاريخ صرف الشيك']);
  const yr            = t['سنة الانشاء'] ?? 'NULL';
  const mo            = t['شهر  الانشاء'] ?? 'NULL';
  const notes         = esc(t['ملاحظات']);
  const accountCode   = t['كود الحساب'] != null ? t['كود الحساب'] : 'NULL';
  const centerCode    = t['كود البيقوت'] != null ? t['كود البيقوت'] : 'NULL';
  const service       = esc(t['الخدمة']);

  // Uniqueness: supplier_code + transaction_date + entry_type + document_number + center_code + credit + debit
  const uniqueClause = `
    supplier_code = ${supplierCode}
    AND transaction_date = ${txDate}
    AND entry_type = ${entryTp}
    AND document_number ${docNum === 'NULL' ? 'IS NULL' : `= ${docNum}`}
    AND center_code ${centerCode === 'NULL' ? 'IS NULL' : `= ${centerCode}`}
    AND credit = ${credit}
    AND debit = ${debit}
    AND company_id = ${COMPANY_ID}`.trim();

  sqlLines.push(
    `INSERT INTO supplier_transactions ` +
    `(company_id, supplier_code, account_code, center_code, transaction_date, entry_type, ` +
    `document_type, document_number, description, expense_category, equipment, unit, quantity, unit_price, ` +
    `amount, credit, debit, check_amount, due_date, balance_no_checks, balance_with_checks, ` +
    `check_clearance_date, year, month, notes, status) ` +
    `SELECT ${COMPANY_ID}, ${supplierCode}, ${accountCode}, ${centerCode}, ${txDate}, ${entryTp}, ` +
    `${docType}, ${docNum}, ${description}, ${expCat}, ${equipment}, ${unit}, ${qty}, ${unitPrice}, ` +
    `${amount}, ${credit}, ${debit}, ${checkAmt}, ${dueDate}, ${balNoChk}, ${balWithChk}, ` +
    `${chkClear}, ${yr}, ${mo}, ${notes}, 'posted' ` +
    `WHERE NOT EXISTS (SELECT 1 FROM supplier_transactions WHERE ${uniqueClause});`
  );
  inserted++;
}

sqlLines.push('');
sqlLines.push(`-- ${inserted} INSERT statements generated`);

const sqlContent = sqlLines.join('\n');

// Write SQL file
const outFile = path.join(__dirname, 'migrations', '0068_import_nawat_transactions.sql');
fs.writeFileSync(outFile, sqlContent, 'utf8');
console.log(`✅ SQL written to: ${outFile}`);
console.log(`📊 ${inserted} INSERT statements generated`);

// Optional: execute immediately against remote D1
const args = process.argv.slice(2);
if (args.includes('--execute')) {
  console.log('\n🚀 Executing against remote D1...');
  try {
    // Split into batches of 50 (D1 has a statement limit per request)
    const allInserts = sqlLines.filter(l => l.startsWith('INSERT'));
    const batchSize = 50;
    let totalDone = 0;

    for (let i = 0; i < allInserts.length; i += batchSize) {
      const batch = allInserts.slice(i, i + batchSize).join('\n');
      const tmpFile = path.join(__dirname, '_tmp_batch.sql');
      fs.writeFileSync(tmpFile, batch, 'utf8');
      execSync(
        `npx wrangler d1 execute ${DB_NAME} --remote --yes --file "${tmpFile}"`,
        { stdio: 'inherit', cwd: __dirname }
      );
      totalDone += Math.min(batchSize, allInserts.length - i);
      console.log(`  ✓ Batch ${Math.ceil((i+1)/batchSize)}: ${totalDone}/${allInserts.length} done`);
    }
    fs.unlinkSync(path.join(__dirname, '_tmp_batch.sql'));
    console.log(`\n✅ All ${totalDone} transactions imported successfully`);
  } catch (err) {
    console.error('❌ Import failed:', err.message);
    process.exit(1);
  }
} else {
  console.log('\nTo execute: node import_nawat_transactions.js --execute');
}
