-- Update chart_of_accounts with mapping data
-- Generated: 2026-04-29T19:55:04.932Z

-- Add mapping column (safe approach for D1)
-- Note: If column already exists, this line will error. Check first with PRAGMA.
ALTER TABLE chart_of_accounts ADD COLUMN account_group TEXT;

UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11010001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11020001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11030001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11040001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11050001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11060001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11070001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11080001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11090001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '11100001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '13010001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '13020001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '13050001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010101' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010150' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010180' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010201' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010301' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010302' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010303' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010304' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14010401' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14010501' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14010502' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010601' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'النقدية ومافي حكمها' WHERE code = '14010602' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'اوراق القبض' WHERE code = '14020001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'اوراق القبض' WHERE code = '14020004' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030101' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030201' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030202' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030203' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030204' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030501' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030502' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030503' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '14030504' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'اطراف ذوي علاقة مدين' WHERE code = '14040101' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'اطراف ذوي علاقة مدين' WHERE code = '14040102' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'اطراف ذوي علاقة مدين' WHERE code = '14040103' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'اطراف ذوي علاقة مدين' WHERE code = '14040104' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'جاري المساهمين' WHERE code = '14040186' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'جاري المساهمين' WHERE code = '14040187' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'جاري المساهمين' WHERE code = '14040188' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040201' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040202' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040203' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040204' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040205' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040206' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040207' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040208' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040209' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040211' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040212' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040213' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040214' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040215' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040216' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040217' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040218' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040219' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040220' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040221' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040222' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040223' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '140403001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '140403002' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '140403003' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '140403004' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '140403005' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040701' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040702' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040703' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '14040704' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات غير المتداولة' WHERE code = '14040705' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040706' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040707' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '14040709' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المخزون' WHERE code = '14070101' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المخزون' WHERE code = '14070102' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المخزون' WHERE code = '14070103' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المخزون' WHERE code = '14070104' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المخزون' WHERE code = '14070105' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المخزون' WHERE code = '14070106' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '21010001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '21020001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '21030001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '21050001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '212000010' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000011' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000012' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000013' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '212000014' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000015' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000016' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000017' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000018' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000019' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000020' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000021' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000022' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000023' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000024' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000025' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000026' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000027' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000028' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الموردين' WHERE code = '212000029' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22020001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22030001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22040001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22050001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22060001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22070001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22080001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22090001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الأصول الثابتة' WHERE code = '22100001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '23010001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '23010002' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'المدينون والارصدة المدينة الاخري' WHERE code = '23010003' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '23010004' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '23010005' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'الالتزامات المتداولة' WHERE code = '23010006' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'اطراف ذوي علاقة مدين' WHERE code = '23010007' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'عملاء' WHERE code = '23010008' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'حقوق الملكية' WHERE code = '25010001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'حقوق الملكية' WHERE code = '25020001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'حقوق الملكية' WHERE code = '25020050' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'حقوق الملكية' WHERE code = '25030001' AND company_id = 1;
UPDATE chart_of_accounts SET account_group = 'حقوق الملكية' WHERE code = '25050001' AND company_id = 1;

-- Total accounts updated: 131
