name               = "agri-nile-flow"
main               = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory          = "./web/dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding       = "DB"
database_name = "nawa-agro-ledger"
database_id   = "b2e5f26c-1aa8-469e-b84a-c291f5eb9cdd"

[vars]
JWT_SECRET = "REPLACE_WITH_STRONG_SECRET_BEFORE_DEPLOY"
APP_ENV    = "production"

[dev]
port           = 8787
local_protocol = "http"
