-- Migration: 0126_schema_migrations_registry
-- Purpose: Create schema_migrations registry table and backfill all 151 existing files
-- Invariant: Every applied migration file is recorded; duplicates are rejected by UNIQUE
-- Safe to apply live: YES (DDL + INSERTs with ON CONFLICT DO NOTHING)
-- Reversible: YES (DROP TABLE schema_migrations)

CREATE TABLE IF NOT EXISTS schema_migrations (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  filename      TEXT    NOT NULL,
  name          TEXT    NOT NULL,
  source        TEXT    NOT NULL DEFAULT 'manual',  -- 'manual' | 'backfill' | 'ci'
  applied_at    TEXT    NOT NULL DEFAULT (datetime('now')),
  UNIQUE(filename)
);

-- Backfill: register all 151 existing migration files as already applied.
-- ON CONFLICT DO NOTHING makes this idempotent.
INSERT OR IGNORE INTO schema_migrations (filename, name, source) VALUES
('001_constraints_staging_audit.sql', '001_constraints_staging_audit', 'backfill'),
('0010_field_season_budgets.sql', '0010_field_season_budgets', 'backfill'),
('0011_supplier_invoices.sql', '0011_supplier_invoices', 'backfill'),
('0012_wo_templates.sql', '0012_wo_templates', 'backfill'),
('0013_ap_aging.sql', '0013_ap_aging', 'backfill'),
('0014_season_close.sql', '0014_season_close', 'backfill'),
('0015_tx_status_workflow.sql', '0015_tx_status_workflow', 'backfill'),
('0016_season_close_fields.sql', '0016_season_close_fields', 'backfill'),
('0017_cash_center_code.sql', '0017_cash_center_code', 'backfill'),
('0018_po_item_code_fix.sql', '0018_po_item_code_fix', 'backfill'),
('0019_backfill_inventory_transactions.sql', '0019_backfill_inventory_transactions', 'backfill'),
('0019_invoice_gr_link.sql', '0019_invoice_gr_link', 'backfill'),
('002_hr_schema_branches.sql', '002_hr_schema_branches', 'backfill'),
('0020_cleanup_and_consistency.sql', '0020_cleanup_and_consistency', 'backfill'),
('0020_historical_operational_reconstruction.sql', '0020_historical_operational_reconstruction', 'backfill'),
('0021_observability.sql', '0021_observability', 'backfill'),
('0022_season_guards.sql', '0022_season_guards', 'backfill'),
('0023_rbac_seeding.sql', '0023_rbac_seeding', 'backfill'),
('0024_fix_missing_ledger_tables.sql', '0024_fix_missing_ledger_tables', 'backfill'),
('0025_standardize_status_columns.sql', '0025_standardize_status_columns', 'backfill'),
('0026_supplier_status_fix.sql', '0026_supplier_status_fix', 'backfill'),
('0027_payroll_payment_fields.sql', '0027_payroll_payment_fields', 'backfill'),
('0028_contract_advance_gl.sql', '0028_contract_advance_gl', 'backfill'),
('0029_add_gl_dimensions.sql', '0029_add_gl_dimensions', 'backfill'),
('003_documents.sql', '003_documents', 'backfill'),
('0030_gl_integration_settings.sql', '0030_gl_integration_settings', 'backfill'),
('0030_inventory_governance.sql', '0030_inventory_governance', 'backfill'),
('0031_gl_structure_fix_phase1_p_l_mapping.sql', '0031_gl_structure_fix_phase1_p_l_mapping', 'backfill'),
('0031_payroll_season_id.sql', '0031_payroll_season_id', 'backfill'),
('0032_cash_field_id.sql', '0032_cash_field_id', 'backfill'),
('0032_gl_structure_fix_phase2_supplier_bridge.sql', '0032_gl_structure_fix_phase2_supplier_bridge', 'backfill'),
('0033_gl_structure_fix_phase3_expense_bridge.sql', '0033_gl_structure_fix_phase3_expense_bridge', 'backfill'),
('0033_rbac_gaps.sql', '0033_rbac_gaps', 'backfill'),
('0034_fixed.sql', '0034_fixed', 'backfill'),
('0034_gl_structure_fix_phase4_dimension_enforcement.sql', '0034_gl_structure_fix_phase4_dimension_enforcement', 'backfill'),
('0034_po_items_center_invoice_unique.sql', '0034_po_items_center_invoice_unique', 'backfill'),
('0034_temp.sql', '0034_temp', 'backfill'),
('0035_inventory_warehouses_and_quants.sql', '0035_inventory_warehouses_and_quants', 'backfill'),
('0036_inventory_enterprise_features.sql', '0036_inventory_enterprise_features', 'backfill'),
('0037_treasury_accounts_and_partners.sql', '0037_treasury_accounts_and_partners', 'backfill'),
('0038_contract_advances_table.sql', '0038_contract_advances_table', 'backfill'),
('0039_unique_local_ids_and_linkage.sql', '0039_unique_local_ids_and_linkage', 'backfill'),
('004_geo_fields_location_tasks.sql', '004_geo_fields_location_tasks', 'backfill'),
('0040_dlce_mapping_rules.sql', '0040_dlce_mapping_rules', 'backfill'),
('0041_posting_groups.sql', '0041_posting_groups', 'backfill'),
('0042_posting_groups_phase4_schema.sql', '0042_posting_groups_phase4_schema', 'backfill'),
('0043_gl_performance_indexes.sql', '0043_gl_performance_indexes', 'backfill'),
('0044_entity_posting_group_indexes.sql', '0044_entity_posting_group_indexes', 'backfill'),
('0045_fix_purchase_orders_fk.sql', '0045_fix_purchase_orders_fk', 'backfill'),
('0046_backfill_inventory_journal_links.sql', '0046_backfill_inventory_journal_links', 'backfill'),
('0047_cost_centers_unique_code_index.sql', '0047_cost_centers_unique_code_index', 'backfill'),
('0048_unified_posting_rules_and_business_events.sql', '0048_unified_posting_rules_and_business_events', 'backfill'),
('0049_migrate_legacy_posting_setup_to_posting_rules.sql', '0049_migrate_legacy_posting_setup_to_posting_rules', 'backfill'),
('005_calendar_tasks.sql', '005_calendar_tasks', 'backfill'),
('0050_drop_legacy_posting_tables.sql', '0050_drop_legacy_posting_tables', 'backfill'),
('0051_posting_engine_phase1_basics.sql', '0051_posting_engine_phase1_basics', 'backfill'),
('0051_posting_engine_phase1_basics_CORRECTED.sql', '0051_posting_engine_phase1_basics_CORRECTED', 'backfill'),
('0051_rule_slot_trace_integrity.sql', '0051_rule_slot_trace_integrity', 'backfill'),
('0052_gl_integrity_triggers_and_indexes.sql', '0052_gl_integrity_triggers_and_indexes', 'backfill'),
('0052_master_data_tables.sql', '0052_master_data_tables', 'backfill'),
('0053_gl_source_tracking_schema.sql', '0053_gl_source_tracking_schema', 'backfill'),
('0054_gl_backfill_simplified.sql', '0054_gl_backfill_simplified', 'backfill'),
('0054_gl_backfill_source_tracking.sql', '0054_gl_backfill_source_tracking', 'backfill'),
('0054_gl_backfill_source_tracking_fixed.sql', '0054_gl_backfill_source_tracking_fixed', 'backfill'),
('0055_seed_deferred_revenue_control.sql', '0055_seed_deferred_revenue_control', 'backfill'),
('0056_wip_balances.sql', '0056_wip_balances', 'backfill'),
('0057_fixed_assets.sql', '0057_fixed_assets', 'backfill'),
('0058_coa_hierarchy_enforcement_and_closure.sql', '0058_coa_hierarchy_enforcement_and_closure', 'backfill'),
('0058_equipment_module_complete.sql', '0058_equipment_module_complete', 'backfill'),
('0059_coa_self_fk_rebuild.sql', '0059_coa_self_fk_rebuild', 'backfill'),
('006_bank_recon_purchase_orders.sql', '006_bank_recon_purchase_orders', 'backfill'),
('0060_add_missing_journal_entry_id_columns.sql', '0060_add_missing_journal_entry_id_columns', 'backfill'),
('0060_exchange_rates_and_gl_journal_audit.sql', '0060_exchange_rates_and_gl_journal_audit', 'backfill'),
('0060_exchange_rates_clean.sql', '0060_exchange_rates_clean', 'backfill'),
('0061_source_documents_bridge.sql', '0061_source_documents_bridge', 'backfill'),
('0062_account_balances_and_batch_post_jobs.sql', '0062_account_balances_and_batch_post_jobs', 'backfill'),
('0063_inventory_rules_wip_finished_accounts.sql', '0063_inventory_rules_wip_finished_accounts', 'backfill'),
('0064_fix_role_permissions_gaps.sql', '0064_fix_role_permissions_gaps', 'backfill'),
('0065_fix_stock_balances_view.sql', '0065_fix_stock_balances_view', 'backfill'),
('0066_inventory_items_master_and_adjustments.sql', '0066_inventory_items_master_and_adjustments', 'backfill'),
('0067_nawat_almustaqbal_data_alignment.sql', '0067_nawat_almustaqbal_data_alignment', 'backfill'),
('0068_import_nawat_transactions.sql', '0068_import_nawat_transactions', 'backfill'),
('0069_sprint1_data_layer_fixes.sql', '0069_sprint1_data_layer_fixes', 'backfill'),
('007_sprint3_gl_links.sql', '007_sprint3_gl_links', 'backfill'),
('0070_sprint2_coa_and_control_fixes.sql', '0070_sprint2_coa_and_control_fixes', 'backfill'),
('0071_backfill_cash_gl_reclassification.sql', '0071_backfill_cash_gl_reclassification', 'backfill'),
('0071_inventory_posting_controls_and_outbox.sql', '0071_inventory_posting_controls_and_outbox', 'backfill'),
('0072_posting_rules_structural_fixes.sql', '0072_posting_rules_structural_fixes', 'backfill'),
('0073_coa_deferred_revenue_and_ap_split.sql', '0073_coa_deferred_revenue_and_ap_split', 'backfill'),
('0074_inventory_posting_group_accounts.sql', '0074_inventory_posting_group_accounts', 'backfill'),
('0075_period_close_governance.sql', '0075_period_close_governance', 'backfill'),
('0077_inventory_schema_hardening.sql', '0077_inventory_schema_hardening', 'backfill'),
('0078_balance_rebuild_and_gl_backfill.sql', '0078_balance_rebuild_and_gl_backfill', 'backfill'),
('0079_backfill_transaction_headers.sql', '0079_backfill_transaction_headers', 'backfill'),
('008_harvest_r2.sql', '008_harvest_r2', 'backfill'),
('0080_fix_control_account_codes.sql', '0080_fix_control_account_codes', 'backfill'),
('0081_backfill_phantom_account_codes.sql', '0081_backfill_phantom_account_codes', 'backfill'),
('0082_fix_ghost_gl_movements.sql', '0082_fix_ghost_gl_movements', 'backfill'),
('0083_reconcile_balance_snapshots.sql', '0083_reconcile_balance_snapshots', 'backfill'),
('0084_phase0_foundations.sql', '0084_phase0_foundations', 'backfill'),
('0085_phase4_transaction_headers.sql', '0085_phase4_transaction_headers', 'backfill'),
('0086_period_inventory_snapshot.sql', '0086_period_inventory_snapshot', 'backfill'),
('0087_supplier_transactions_payment_and_equipment_mode.sql', '0087_supplier_transactions_payment_and_equipment_mode', 'backfill'),
('0088_work_order_equipment.sql', '0088_work_order_equipment', 'backfill'),
('0089_wo_template_equipment.sql', '0089_wo_template_equipment', 'backfill'),
('009_source_documents_bridge.sql', '009_source_documents_bridge', 'backfill'),
('0090_fixed_assets_season_and_wip_carry.sql', '0090_fixed_assets_season_and_wip_carry', 'backfill'),
('0091_work_orders_center_code_and_equipment_linkage.sql', '0091_work_orders_center_code_and_equipment_linkage', 'backfill'),
('0092_operation_types.sql', '0092_operation_types', 'backfill'),
('0093_work_order_equipment_journal_link.sql', '0093_work_order_equipment_journal_link', 'backfill'),
('0094_coa_governance_phase.sql', '0094_coa_governance_phase', 'backfill'),
('0095_data_quality_control.sql', '0095_data_quality_control', 'backfill'),
('0096_gl_module_views.sql', '0096_gl_module_views', 'backfill'),
('0097_week1_db_safety_hardening.sql', '0097_week1_db_safety_hardening', 'backfill'),
('0098_fix_equipment_type_orphan.sql', '0098_fix_equipment_type_orphan', 'backfill'),
('0099_season_id_backfill.sql', '0099_season_id_backfill', 'backfill'),
('0100_service_taxonomy_and_supplier_map.sql', '0100_service_taxonomy_and_supplier_map', 'backfill'),
('0100_week2_bpg_supplier_backfill.sql', '0100_week2_bpg_supplier_backfill', 'backfill'),
('0101_inventory_governance_columns.sql', '0101_inventory_governance_columns', 'backfill'),
('0101_week4_grn_dimension_backfill.sql', '0101_week4_grn_dimension_backfill', 'backfill'),
('0102_inventory_governance_index.sql', '0102_inventory_governance_index', 'backfill'),
('0102_work_order_equipment_operation_idempotency.sql', '0102_work_order_equipment_operation_idempotency', 'backfill'),
('0103_supplier_txn_service_type_column.sql', '0103_supplier_txn_service_type_column', 'backfill'),
('0104_backfill_supplier_txn_service_type.sql', '0104_backfill_supplier_txn_service_type', 'backfill'),
('0105_backfill_inventory_service_type.sql', '0105_backfill_inventory_service_type', 'backfill'),
('0106_reclassify_supplier_20900151_ap.sql', '0106_reclassify_supplier_20900151_ap', 'backfill'),
('0107_reclass_supplier_20900151_to_srv_supply_ap.sql', '0107_reclass_supplier_20900151_to_srv_supply_ap', 'backfill'),
('0108_sprint2_cogs_and_ap_aging.sql', '0108_sprint2_cogs_and_ap_aging', 'backfill'),
('0109_supplier_ap_ledger_and_matching.sql', '0109_supplier_ap_ledger_and_matching', 'backfill'),
('0110_unit_types_and_form_schema.sql', '0110_unit_types_and_form_schema', 'backfill'),
('0111_items_governance_and_cogs_safety.sql', '0111_items_governance_and_cogs_safety', 'backfill'),
('0112_archive_future_blocked_and_phase_b_backfill.sql', '0112_archive_future_blocked_and_phase_b_backfill', 'backfill'),
('0113_freeze_expense_types.sql', '0113_freeze_expense_types', 'backfill'),
('0114_freeze_expense_types_write_block.sql', '0114_freeze_expense_types_write_block', 'backfill'),
('0115_emergency_fixup.sql', '0115_emergency_fixup', 'backfill'),
('0116_phase_b_data_backfill.sql', '0116_phase_b_data_backfill', 'backfill'),
('0117_backfill_flag_columns.sql', '0117_backfill_flag_columns', 'backfill'),
('0118_schema_hardening_pre_import.sql', '0118_schema_hardening_pre_import', 'backfill'),
('0119_operational_wipe.sql', '0119_operational_wipe', 'backfill'),
('0120_standard_uom_and_ap_cleanup.sql', '0120_standard_uom_and_ap_cleanup', 'backfill'),
('0121_fix_ap_ledger_entry_type.sql', '0121_fix_ap_ledger_entry_type', 'backfill'),
('0122_gl_trace_columns.sql', '0122_gl_trace_columns', 'backfill'),
('0123_fields_crop_name.sql', '0123_fields_crop_name', 'backfill'),
('0124_inventory_runtime_stabilization.sql', '0124_inventory_runtime_stabilization', 'backfill'),
('0124_wipe_smoke_certification_data.sql', '0124_wipe_smoke_certification_data', 'backfill'),
('0125_gl_line_financial_update_trigger.sql', '0125_gl_line_financial_update_trigger', 'backfill'),
('0126_schema_migrations_registry.sql', '0126_schema_migrations_registry', 'backfill');

-- REVERSE:
-- DROP TABLE IF EXISTS schema_migrations;
