INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010004, 1, 'سلفات النشادر محبب', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010366, 1, 'سوبر  فوسفات محبب', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030002, 1, 'تقاوى بنجر جوستاف', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030260, 1, 'تقاوي بنجر استخيا', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030234, 1, 'تقاوى بنجر فنجينس', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030229, 1, 'تقاوي بنجر تايسون', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030259, 1, 'تقاوي بنجر المو', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030003, 1, 'تقاوى بنجر اسكوتا', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1050197, 1, 'بوش 2" بلاستيك/1"', 'وحدة', 'شبكات ري', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1050401, 1, 'بوش 1" * 2/1 " بلاستيك', 'وحدة', 'شبكات ري', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1050364, 1, 'نبل 1/2" بلاستيك', 'وحدة', 'شبكات ري', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1070010, 1, 'قفيز حرف U كبير', 'وحدة', 'قطع غيار', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1070317, 1, 'سيلكون اسود', 'وحدة', 'قطع غيار', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1080035, 1, 'خيط دبارة ( مسلة)', 'كجم', 'تعبئة وتغليف', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1090168, 1, 'ماسورة 1" بولي', 'وحدة', 'متنوعات', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1040001, 1, 'سولار', 'لتر', 'زيوت ووقود', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1070238, 1, 'شريط لحام', 'وحدة', 'قطع غيار', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1070786, 1, 'سرفيل 50 نحاس', 'وحدة', 'قطع غيار', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1070245, 1, 'اسكوتش', 'وحدة', 'قطع غيار', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010095, 1, 'يوريا', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010006, 1, 'حمض كبرتيك', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010002, 1, 'حمض فسفوريك', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010189, 1, 'اي جي امينو(احماض امينيه)', 'لتر', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010436, 1, 'فيروكس (منشط جزور)', 'لتر', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1020361, 1, 'مارفل ( معالج ملوحة )', 'لتر', 'مبيدات', 1, 'CHEM');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010074, 1, 'نترات ابوقير', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010060, 1, 'ماب', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010066, 1, 'حامض نيتريك', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1020362, 1, 'نصر بروكسيد(ماء اكسجين)', 'لتر', 'مبيدات', 1, 'CHEM');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010132, 1, 'نترات كالسيوم محبب صيني', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1050095, 1, 'نبل بلاستيك 4/3"', 'وحدة', 'شبكات ري', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1050316, 1, 'محبس 3\4 سن', 'وحدة', 'شبكات ري', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010075, 1, 'بوتاسيوم 0050', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030008, 1, 'تقاوى بنجر جنيو', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010374, 1, 'فيرتك 19-19-19', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010071, 1, 'هيومك', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010062, 1, 'فولفيك', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1070844, 1, 'مفتاح كهرباء', 'وحدة', 'قطع غيار', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1090043, 1, 'لمبه 9 وات', 'وحدة', 'متنوعات', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030267, 1, 'تقاوي بنجر بي تي اس 7870', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030264, 1, 'تقاوي بنجر ماتروس', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030265, 1, 'تقاوي بنجر Pitt', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030233, 1, 'تقاوى بنجر برسيا', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030266, 1, 'تقاوي بنجر دنزيل', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010438, 1, 'اي جي سي انيتروبي اس', 'لتر', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010439, 1, 'اي جي مالتي ميكس (مكس عناصر)', 'لتر', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010023, 1, 'سلفات ماغنسيوم', 'كجم', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1090228, 1, 'صرف قاعده سوسته', 'وحدة', 'متنوعات', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1090230, 1, 'كوع سيفون 4"', 'وحدة', 'متنوعات', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1020380, 1, 'ريزوسفير 15', 'لتر', 'مبيدات', 1, 'CHEM');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010437, 1, 'سبلة سير', 'متر', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030274, 1, 'تقاوي بنجر بريليف', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1020259, 1, 'خل', 'لتر', 'مبيدات', 1, 'CHEM');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1020288, 1, 'ساليكس', 'كجم', 'مبيدات', 1, 'CHEM');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1030277, 1, 'تقاوي بنجر امالدي', 'وحدة', 'تقاوي وبذور', 1, 'SEED');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1050092, 1, 'لفة خرطوم 2"', 'وحدة', 'شبكات ري', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1050149, 1, 'قفيز 2" حديد', 'وحدة', 'شبكات ري', 1, 'EQUIP');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1020393, 1, 'هاي كيو', 'لتر', 'مبيدات', 1, 'CHEM');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010449, 1, 'اي جي سي بورامين 15%', 'لتر', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1010327, 1, 'سبيد الجاماكس', 'لتر', 'اسمدة', 1, 'FERT');
INSERT OR REPLACE INTO items (code, company_id, name, unit, warehouse, is_active, prod_posting_group_code) VALUES (1020401, 1, 'لارفا مايورا', 'لتر', 'مبيدات', 1, 'CHEM');
